<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Azure.Identity" />
    <PackageReference Include="Azure.Security.KeyVault.Keys" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DotNetCoreCryptography.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DotNetCoreCryptographyCore\DotNetCoreCryptographyCore.csproj" />
  </ItemGroup>

</Project>
