using DotNetCoreCryptographyCore;
using DotNetCoreCryptographyCore.Concrete;
using System;
using System.IO;
using System.Text;
using System.Threading.Tasks;
using Xunit;

namespace DotNetCoreCryptography.Tests.Core
{
    /// <summary>
    /// Backward-compatibility tests: the fixture files under Core/Fixtures/v1 were
    /// generated by the library BEFORE the authenticated (v2, AES-GCM) format was
    /// introduced, so these tests prove that genuinely old (v1, AES-CBC) data is
    /// still readable. Do not regenerate the fixtures with current code.
    /// </summary>
    public class V1CompatibilityTests
    {
        private const string FixturePlaintext = "This is the DotNetCoreCryptography v1 compatibility fixture plaintext. It spans multiple AES blocks to exercise CBC chaining and PKCS7 padding. 0123456789.";
        private const string FixturePassword = "fixture-password";

        private static readonly string FixtureDir = Path.Combine(AppContext.BaseDirectory, "Core", "Fixtures", "v1");

        private static byte[] ReadFixture(string name)
        {
            return File.ReadAllBytes(Path.Combine(FixtureDir, name));
        }

        [Fact]
        public void Can_decrypt_v1_stream_encrypted_with_serialized_key()
        {
            using var key = EncryptionKey.CreateFromSerializedVersion(ReadFixture("v1-aes-cbc.key"));
            using var source = new MemoryStream(ReadFixture("v1-static-key.bin"));
            using var destination = new MemoryStream();
            StaticEncryptor.Decrypt(source, destination, key);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(destination.ToArray()));
        }

        [Fact]
        public void Can_decrypt_v1_password_data()
        {
            var decrypted = StaticEncryptor.AesDecryptWithPassword(ReadFixture("v1-password.bin"), FixturePassword);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(decrypted));
        }

        [Fact]
        public async Task Can_decrypt_v1_password_data_async()
        {
            var decrypted = await StaticEncryptor.AesDecryptWithPasswordAsync(ReadFixture("v1-password.bin"), FixturePassword);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(decrypted));
        }

        [Fact]
        public async Task Can_decrypt_v1_envelope_with_folder_based_key_encryptor()
        {
            var keyEncryptor = new FolderBasedKeyEncryptor(Path.Combine(FixtureDir, "folder"), FixturePassword);
            var secureEncryptor = new SecureEncryptor(keyEncryptor);
            using var source = new MemoryStream(ReadFixture("v1-folder-envelope.bin"));
            using var destination = new MemoryStream();
            await secureEncryptor.Decrypt(source, destination);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(destination.ToArray()));
        }

        [Fact]
        public async Task Can_unwrap_v1_wrapped_key_blob()
        {
            var keyEncryptor = new FolderBasedKeyEncryptor(Path.Combine(FixtureDir, "folder"), FixturePassword);
            using var expectedKey = EncryptionKey.CreateFromSerializedVersion(ReadFixture("v1-folder-wrappedkey-dek.key"));
            using var unwrapped = await keyEncryptor.DecryptAsync(ReadFixture("v1-folder-wrappedkey.bin"));
            Assert.Equal(expectedKey, unwrapped);
        }

        [Fact]
        public async Task Can_decrypt_v1_envelope_with_developer_key_encryptor()
        {
            var keyEncryptor = new DeveloperKeyEncryptor(Path.Combine(FixtureDir, "developer"), allowUnencryptedKeyStore: true);
            var secureEncryptor = new SecureEncryptor(keyEncryptor);
            using var source = new MemoryStream(ReadFixture("v1-developer-envelope.bin"));
            using var destination = new MemoryStream();
            await secureEncryptor.Decrypt(source, destination);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(destination.ToArray()));
        }

        [Fact]
        public async Task Can_decrypt_v1_asymmetric_envelope()
        {
            using var key = AsymmetricEncryptionKey.CreateFromSerializedVersion(ReadFixture("v1-rsa.key"));
            using var source = new MemoryStream(ReadFixture("v1-asymmetric-envelope.bin"));
            using var destination = new MemoryStream();
            await AsymmetricSecureEncryptor.Decrypt(key, source, destination);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(destination.ToArray()));
        }

        [Fact]
        public async Task Legacy_key_store_wraps_new_blobs_in_v2_format()
        {
            //the fixture store contains a legacy (CBC) key-encryption key: new blobs
            //must still be wrapped with the authenticated v2 format (AES-KWP).
            var keyEncryptor = new FolderBasedKeyEncryptor(Path.Combine(FixtureDir, "folder"), FixturePassword);
            using var key = EncryptionKey.CreateDefault();
            var wrapped = await keyEncryptor.EncryptAsync(key);
            using var unwrapped = await keyEncryptor.DecryptAsync(wrapped);
            Assert.Equal(key, unwrapped);
        }

        [Fact]
        public async Task New_envelopes_written_with_legacy_key_store_roundtrip()
        {
            var keyEncryptor = new FolderBasedKeyEncryptor(Path.Combine(FixtureDir, "folder"), FixturePassword);
            var secureEncryptor = new SecureEncryptor(keyEncryptor);
            using var source = new MemoryStream(Encoding.UTF8.GetBytes(FixturePlaintext));
            using var encrypted = new MemoryStream();
            await secureEncryptor.Encrypt(source, encrypted);

            using var encryptedSource = new MemoryStream(encrypted.ToArray());
            using var destination = new MemoryStream();
            await secureEncryptor.Decrypt(encryptedSource, destination);
            Assert.Equal(FixturePlaintext, Encoding.UTF8.GetString(destination.ToArray()));
        }
    }
}
