name: BuildAndPublish_template
on:
  push:
    branches:
      - master
      - develop
      - feature/*
      - hotfix/*
      - release/*
  pull_request: 

jobs:
  call-build-and-publish:
    uses: alkampfergit/workflows/.github/workflows/dotnet-library.yml@master
    with:
      coverage_info_dir: ./src/DotNetCoreCryptography.Tests/TestResults/coverage.info 
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}